class StartPageConsts:
    ELEMENTS_CARD_XPATH = './/div[h5[text()="Elements"]]'
    FORMS_CARD_XPATH = './/div[h5[text()="Forms"]]'
    ALERTS_FRAMES_WINDOWS_CARD_XPATH = './/div[h5[text()="Alerts, Frame & Windows"]]'
    WIDGETS_CARD_XPATH = './/div[h5[text()="Widgets"]]'
    INTERACTIONS_CARD_XPATH = './/div[h5[text()="Interactions"]]'
    BOOK_STORE_APPLICATION_CARD_XPATH = './/div[h5[text()="Book Store Application"]]'
    # Text Box Consts
    TEXT_BOX_SECTION_XPATH = './/span[text()="Text Box"]'
    TEXT_BOX_FULL_NAME_XPATH = './/*[@placeholder="Full Name"]'
    EMAIL_INPUT_FIELD_XPATH = '//*[@id="userEmail"]'
    EMAIL_FIELD_ERROR_XPATH = './/*[@class="mr-sm-2 field-error form-control"]'
    CURRENT_ADDRESS_FIELD_XPATH = './/*[@placeholder="Current Address"]'
    PERMANENT_ADDRESS_FIELD_XPATH = '//*[@id="permanentAddress"]'
    SUBMIT_BUTTON_XPATH = '//*[@id="submit"]'
    OUTPUT_AREA_XPATH = '//*[@id="output"]|*[text()="{output_text}"]'
    # Check Box Consts
    CHECK_BOX_SECTION_XPATH = './/span[text()="Check Box"]'
    EXPAND_ALL_XPATH = './/*[@class="rct-icon rct-icon-expand-all"]'
    COLLAPSE_ALL_XPATH = './/*[@class="rct-icon rct-icon-collapse-all"]'
    HOME_DIR_XPATH = './/*[text()=Home"]'
    HOME_EXPAND_XPATH = './/*/div/ol/li/span/button'
    DESKTOP_DIR_XPATH = './/*[text()="Desktop"]'
    DESKTOP_EXPAND_XPATH = './/*/li[1]/span/button'
    NOTES_XPATH = './/*[text()="Notes"]'
    COMMANDS_XPATH = './/*[text()="Commands"]'
    DOCUMENTS_DIR_XPATH = './/*[text()="Documents"]'
    DOCUMENTS_EXPAND_XPATH = './/*/li[2]/span/button'
    WORKSPACE_DIR_XPATH = './/*[text()="WorkSpace"]'
    WORKSPACE_EXPAND_XPATH = './/*/li[2]/ol/li[1]/span/button'
    REACT_XPATH = './/*[text()="React"]'
    ANGULAR_XPATH = './/*[text()="Angular"]'
    VEU_XPATH = './/*[text()="Veu"]'
    OFFICE_DIR_XPATH = './/*[text()="Office"]'
    OFFICE_EXPAND_XPATH = './/*/li[2]/ol/li[2]/span/button'
    PUBLIC_XPATH = './/*[text()="Public"]'
    PRIVATE_XPATH = './/*[text()="Private"]'
    CLASSIFIED_XPATH = './/*[text()="Classified"]'
    GENERAL_XPATH = './/*[text()="General"]'
    DOWNLOADS_DIR_XPATH = './/*[text()="Downloads"]'
    DOWNLOADS_EXPAND_XPATH = './/*/li[3]/span/button'
    WORD_FILE_XPATH = './/*[text()="Word File.doc"]'
    EXCEL_FILE_XPATH = './/*[text()="Excel File.doc"]'
    RESULT_XPATH = './/div[@id="result"]'
